[font]
  normal = {family = "JetBrainsMono NF" ,style = "Regular"}
  bold = {family = "JetBrainsMono NF" ,style = "Bold"}
  italic  = {family = "JetBrainsMono NF" ,style = "Italic "}
  bold_italic  = {family = "JetBrainsMono NF" ,style = "Bold Italic "}
  size = 12

[window]
  dimensions = {columns = 110 , lines = 25}

[keyboard]
  bindings = [{key = "N", mods = "Control | Shift" , action = "CreateNewWindow" }]


# Colors (Nord)

# Default colors
[colors.primary]
background = '#2E3440'
foreground = '#D8DEE9'

# Normal colors
[colors.normal]
black   = '#3B4252'
red     = '#BF616A'
green   = '#A3BE8C'
yellow  = '#EBCB8B'
blue    = '#81A1C1'
magenta = '#B48EAD'
cyan    = '#88C0D0'
white   = '#E5E9F0'

# Bright colors
[colors.bright]
black   = '#4C566A'
red     = '#BF616A'
green   = '#A3BE8C'
yellow  = '#EBCB8B'
blue    = '#81A1C1'
magenta = '#B48EAD'
cyan    = '#8FBCBB'
white   = '#ECEFF4'

[env]
  WINIT_X11_SCALE_FACTOR = "1.0"
